name: loteria.deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_path: ${{ steps.upload-artifact.outputs.build_path }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Check Build Directory
        run: |
          # List files in the current directory for debugging
          echo "Listing files in the current directory:"
          ls -R

          # Check if the build directory exists
          if [ -d "build" ]; then
            echo "Build directory found."
          else
            echo "Build directory not found. Check if the artifact was downloaded correctly."
            exit 1
          fi

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=build --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "Deployed via GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
