name: loteria.deploy

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
             
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.30.0'

            - name: Install dependencies
              run: npm install
             
            - name: Build
              run: npm run build
             
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: react-build
                path: build/

    deploy-loteria:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Netlify CLI
              run: npm install -g netlify-cli

            - name: Deploy to Netlify
              run: netlify deploy --prod --dir=build --auth ${{ secrets.nfp_8vxUBkJavsQmXjGPBP52xYbMid4g1t8y9749 }} --site ${{ secrets.c3e4fa0c-bc41-4cd9-b83a-1b42044f1048 }}
              env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.nfp_8vxUBkJavsQmXjGPBP52xYbMid4g1t8y9749}}
                NETLIFY_SITE_ID: ${{ secrets.c3e4fa0c-bc41-4cd9-b83a-1b42044f1048}}