name: loteria.deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Repositorio Checkout
          uses: actions/checkout@v4

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: "npm"

        - name: Intalar Dependencias
          run: npm install

        - name: Build projeto
          run: npm run build

        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: react-build
            path: build/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with:
              name: react-build
    
        - name: Install Netlify CLI
          run: npm install netlify-cli@17.10.1 

        - name: Deploy Netlify
          run: netlify deploy --prod --dir=build --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}