name: loteria.deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_path: ${{ steps.upload-artifact.outputs.build_path }}
    steps:
      - name: Repositorio Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Instalar Dependências
        run: npm install

      - name: Build Projeto
        run: npm run build

      - name: Upload Build Artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Deploy to Netlify
        run: |
          # Verificar se o diretório build está presente após o download
          if [ -d "build" ]; then
            echo "Diretório de build encontrado."
            netlify deploy --prod --dir=build --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "Deployed via GitHub Actions"
          else
            echo "Diretório de build não encontrado. O deploy falhou."
            exit 1
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
